import type { Artifact, Quest, Tier } from "./types";

const pack = (artifact: Artifact): string => JSON.stringify(artifact);

function planOutputs(
  title: string,
  goal: string,
  strongSteps: string[],
  done: string[],
): Record<Tier, string> {
  return {
    npc: pack({
      kind: "plan",
      title,
      goal: "Complete the task successfully.",
      steps: [
        { n: 1, action: "Start the task." },
        { n: 2, action: "Do the work." },
        { n: 3, action: "Check the result." },
      ],
      doneCriteria: ["The task looks complete."],
    }),
    grinder: pack({
      kind: "plan",
      title,
      goal,
      steps: strongSteps.slice(0, 4).map((action, index) => ({ n: index + 1, action })),
      doneCriteria: done.slice(0, 2),
    }),
    farmer: pack({
      kind: "plan",
      title,
      goal,
      steps: strongSteps.map((action, index) => ({ n: index + 1, action })),
      doneCriteria: done,
    }),
  };
}

function researchOutputs(
  topic: string,
  summary: string,
  facts: { text: string; source?: string }[],
): Record<Tier, string> {
  return {
    npc: pack({
      kind: "research",
      topic,
      summary: "Here is some general information about the topic.",
      facts: facts.slice(0, 2).map(({ text }) => ({ text })),
      citations: [],
    }),
    grinder: pack({
      kind: "research",
      topic,
      summary,
      facts: facts.slice(0, 3),
      citations: facts.flatMap((fact) => (fact.source ? [fact.source] : [])).slice(0, 2),
    }),
    farmer: pack({
      kind: "research",
      topic,
      summary,
      facts,
      citations: facts.flatMap((fact) => (fact.source ? [fact.source] : [])),
    }),
  };
}

export const EXTENDED_QUESTS: Quest[] = [
  // AI FOUNDATIONS
  {
    id: "f1",
    category: "foundations",
    subject: "AI is a family of systems, not one magic brain",
    title: "AI Family Tree",
    tagline: "Rules, ML, GenAI or agent? Sort the squad.",
    task: "Classify each system by the main idea that makes it work.",
    items: [
      {
        id: "f1-1",
        prompt: "A calculator follows fixed instructions to add two numbers. What best describes it?",
        options: ["Rule-based software", "Machine learning", "Generative AI", "AI agent"],
        answerIndex: 0,
        hint: "Did it learn a pattern from examples, or follow steps written in advance?",
        explanation: "Rule-based software. Its steps were written directly by people. It does not learn from data or generate new content.",
      },
      {
        id: "f1-2",
        prompt: "An email filter learns patterns from thousands of labelled spam and non-spam messages.",
        options: ["Rule-based software", "Machine learning", "Generative AI", "AI agent"],
        answerIndex: 1,
        hint: "The important clue is that it learns from labelled examples.",
        explanation: "Machine learning. It learns a pattern that helps it classify new email. It is predicting a label, not creating a new email.",
      },
      {
        id: "f1-3",
        prompt: "A tool creates a new image from the instruction 'a dragon reading in the library'.",
        options: ["Rule-based software", "Machine learning", "Generative AI", "AI agent"],
        answerIndex: 2,
        hint: "Is the system choosing a label, or producing new content?",
        explanation: "Generative AI. It produces new content from patterns learned during training.",
      },
      {
        id: "f1-4",
        prompt: "A system reads a goal, searches the web, updates a spreadsheet and pauses before emailing anyone.",
        options: ["Rule-based software", "Machine learning", "Generative AI", "AI agent"],
        answerIndex: 3,
        hint: "Look for a goal, a sequence of decisions and tools that change something.",
        explanation: "AI agent. The model is part of a loop that plans, uses tools, observes results and decides what to do next.",
      },
      {
        id: "f1-5",
        prompt: "Which statement is most accurate?",
        options: [
          "Every computer program is AI",
          "All AI systems generate text",
          "Generative AI is one part of the wider AI field",
          "An agent and a chatbot are always the same",
        ],
        answerIndex: 2,
        hint: "Think of AI as the largest umbrella.",
        explanation: "Generative AI is one part of AI. AI also includes classifiers, recommenders, planning systems and other approaches.",
      },
    ],
  },
  {
    id: "f2",
    category: "foundations",
    subject: "Models learn patterns from data, then face new examples",
    title: "Train, Test, Try Again",
    tagline: "Teach it, test it, catch the shortcut.",
    task: "Work out what training, testing and evaluation actually reveal.",
    items: [
      {
        id: "f2-1",
        prompt: "A model studies 8,000 labelled plant photos. What is that collection mainly used for?",
        options: ["Training", "Testing", "Prompting", "Fact-checking"],
        answerIndex: 0,
        hint: "This is the set the model learns patterns from.",
        explanation: "Training. The model adjusts itself using examples and labels in the training data.",
      },
      {
        id: "f2-2",
        prompt: "Why should the final test photos be kept separate from the training photos?",
        options: [
          "To make the file smaller",
          "To test performance on genuinely unseen examples",
          "To hide mistakes from the model",
          "To make the model answer faster",
        ],
        answerIndex: 1,
        hint: "A memorised answer is not the same as handling something new.",
        explanation: "A separate test set shows whether the model can generalise. Testing on material it already saw can make performance look misleadingly strong.",
      },
      {
        id: "f2-3",
        prompt: "A plant model is accurate in the lab but fails on dim phone photos. What is the best first suspicion?",
        options: ["The phone is too new", "The training data did not represent real use", "AI cannot process photos", "The labels were alphabetical"],
        answerIndex: 1,
        hint: "Compare the conditions in training with the conditions in real life.",
        explanation: "The data may not represent real use. Lighting, camera quality and backgrounds can create a gap between a test and the real world.",
      },
      {
        id: "f2-4",
        prompt: "A model gets 95% overall accuracy but misses most examples from one group. Is it ready?",
        options: ["Yes, 95% is always enough", "No, check performance across relevant groups", "Yes, averages are objective", "No, because models must reach 100%"],
        answerIndex: 1,
        hint: "An average can hide who receives the errors.",
        explanation: "Check the groups separately. A strong average can hide systematic failure for people or situations underrepresented in the data.",
      },
    ],
  },
  {
    id: "f3",
    category: "foundations",
    subject: "Fluent language can come from prediction without human understanding",
    title: "Prediction Machine",
    tagline: "Sounds smart. What is it actually doing?",
    task: "Build a useful mental model of how a large language model produces an answer.",
    items: [
      {
        id: "f3-1",
        prompt: "At its core, what does a large language model repeatedly predict while writing?",
        options: ["The user's mood", "The next token", "The final truth", "A hidden webpage"],
        answerIndex: 1,
        hint: "Think one small piece of text at a time.",
        explanation: "It predicts the next token, then repeats. Training makes those predictions remarkably useful, but the process does not guarantee truth.",
      },
      {
        id: "f3-2",
        prompt: "Why can the same prompt produce slightly different answers?",
        options: ["The model is moody", "Generation can sample among likely continuations", "The internet changed", "The prompt was deleted"],
        answerIndex: 1,
        hint: "More than one next word can be plausible.",
        explanation: "Generation can sample among several likely continuations. Settings and system instructions can also change which continuation is chosen.",
      },
      {
        id: "f3-3",
        prompt: "A chatbot says, 'I feel worried about that.' What should you infer?",
        options: ["It definitely has feelings", "It is generating language that fits the conversation", "It is lying on purpose", "It needs a break"],
        answerIndex: 1,
        hint: "Separate human-sounding language from evidence of inner experience.",
        explanation: "Treat it as generated conversational language. Human-like wording is not evidence that the system feels emotions or understands as a person does.",
      },
      {
        id: "f3-4",
        prompt: "What is the safest view of a polished AI explanation?",
        options: ["Polish proves expertise", "It is a useful draft that still needs evaluation", "Longer means more accurate", "Confidence means the model checked"],
        answerIndex: 1,
        hint: "Judge the evidence and reasoning, not the writing style.",
        explanation: "Use it as a draft or thinking partner. Fluency and confidence are presentation qualities, not proof.",
      },
    ],
  },
  {
    id: "f4",
    category: "foundations",
    subject: "The best tool depends on the job",
    title: "Model Matchmaker",
    tagline: "Don't bring a chatbot to a calculator fight.",
    task: "Choose the simplest reliable tool for each task.",
    items: [
      {
        id: "f4-1",
        prompt: "You need the exact value of 847 × 293. Which tool should lead?",
        options: ["Calculator", "Image generator", "Chatbot memory", "Recommendation model"],
        answerIndex: 0,
        hint: "Choose the tool designed to produce an exact numeric result.",
        explanation: "Calculator. A language model can explain the method, but exact arithmetic belongs with a deterministic tool.",
      },
      {
        id: "f4-2",
        prompt: "You need today's train disruption status. Which tool should lead?",
        options: ["A model's training memory", "An official live source or search tool", "An image generator", "A spelling checker"],
        answerIndex: 1,
        hint: "The information changes and needs a timestamped source.",
        explanation: "Use an official live source or a search tool that can reach it. Training memory may be old.",
      },
      {
        id: "f4-3",
        prompt: "You want ten unusual themes for a class celebration. Which tool fits best?",
        options: ["Generative AI", "Database lookup only", "Calculator", "Spam classifier"],
        answerIndex: 0,
        hint: "This task benefits from many possible drafts, not one exact answer.",
        explanation: "Generative AI is useful for brainstorming. A human should still select ideas that fit the class, budget and rules.",
      },
      {
        id: "f4-4",
        prompt: "A school must store attendance records accurately for years. What should be the source of truth?",
        options: ["A chatbot conversation", "A structured database", "Generated images", "A model's memory"],
        answerIndex: 1,
        hint: "The system needs stable records that can be retrieved and audited.",
        explanation: "A structured database should hold the records. AI can help query or summarise them with suitable safeguards, but should not replace the source of truth.",
      },
    ],
  },

  // ADVANCED PROMPTING
  {
    id: "p5",
    category: "prompting",
    subject: "Examples can teach a pattern more clearly than adjectives",
    title: "Show, Don't Just Tell",
    tagline: "Two examples. One style. Make the pattern obvious.",
    artifact: "slides",
    task: "SCENARIO: Your class needs three digital notice slides. They must all use the same punchy style, but words like 'fun' and 'cool' keep producing random results.\n\nYOUR TASK: Prompt the agent to create the three slides. Give it two short input-to-output examples that demonstrate the pattern, explain the audience and goal, then specify the format and limits. Your examples should teach the style without writing the three final slides for it.",
    rubric: ["context", "action", "examples", "format", "criteria"],
    mockOutputs: {
      npc: pack({ kind: "slides", title: "School Notices", slides: [{ heading: "Notice", bullets: ["Something is happening soon."] }, { heading: "Another Notice", bullets: ["Please take note."] }, { heading: "Thank You", bullets: ["Have a nice day."] }] }),
      grinder: pack({ kind: "slides", title: "This Week", slides: [{ heading: "CCA Fair lands Friday", bullets: ["Hall, 2.30pm", "Come curious"] }, { heading: "Library closes early", bullets: ["Thursday, 4pm", "Return books before recess"] }, { heading: "Bring your bottle", bullets: ["Refill stations are open", "Skip single-use plastic"] }] }),
      farmer: pack({ kind: "slides", title: "Three notices, one voice", slides: [{ heading: "FRIDAY: FIND YOUR PEOPLE", bullets: ["CCA Fair", "2.30pm · School Hall"], visual: "one bold activity photo with the time oversized" }, { heading: "BOOKS HOME BY RECESS", bullets: ["Library closes 4pm Thursday", "Returns box stays open"], visual: "book stack with one short directional arrow" }, { heading: "REFILL. REPEAT.", bullets: ["Bring your bottle", "Stations beside the canteen"], visual: "bottle silhouette and two-location mini map" }] }),
    },
  },
  {
    id: "p6",
    category: "prompting",
    subject: "A good assistant notices ambiguity before committing",
    title: "Question Me First",
    tagline: "Missing info? Make the agent stop and ask.",
    artifact: "plan",
    task: "SCENARIO: You need an agent to plan a class learning journey, but the date, budget, group size and accessibility needs are still unknown. A confident guess could waste money or exclude someone.\n\nYOUR TASK: Write a prompt that tells the agent what outcome you need, identifies the missing decisions, and makes it ask a small set of high-value questions before proposing a plan. It must wait for answers instead of silently assuming them.",
    rubric: ["context", "goal", "clarifying", "boundaries", "done"],
    mockOutputs: planOutputs("Class Learning Journey", "Produce a feasible, inclusive plan after the organiser answers the blocking questions.", ["Ask for the date, group size and total budget.", "Ask about mobility, sensory, dietary and supervision needs without requesting diagnoses.", "Wait for the organiser's reply before selecting a venue.", "Draft two options that fit the confirmed constraints.", "Flag any remaining assumption beside the part it affects."], ["Every blocking question has an answer or is visibly marked unresolved.", "The final plan fits the confirmed budget and group size.", "No booking or message is sent without approval."]),
  },
  {
    id: "p7",
    category: "prompting",
    subject: "Define good before asking AI to produce it",
    title: "Rubric Rumble",
    tagline: "Set the bar first. Then make the draft clear it.",
    artifact: "research",
    task: "SCENARIO: Your group needs a one-page explainer about food waste for Sec 1 students. Everyone disagrees about what 'good' means.\n\nYOUR TASK: Prompt the agent to create the explainer, but define four checkable success criteria first. Include audience, structure, evidence expectations and a reading-level or length limit. Tell it to self-check against those criteria and report one weakness, not to award itself a perfect score.",
    rubric: ["context", "action", "criteria", "sources", "uncertainty"],
    mockOutputs: researchOutputs("Food waste", "A one-page student explainer that connects everyday choices with practical action and separates sourced facts from suggestions.", [{ text: "Define food waste in plain language before using statistics.", source: "Singapore National Environment Agency" }, { text: "Use one current local statistic only after checking its year and source.", source: "nea.gov.sg" }, { text: "Include three actions a student can take during a school lunch." }, { text: "Self-check weakness: the draft needs a student example to make the advice easier to picture." }]),
  },
  {
    id: "p8",
    category: "prompting",
    subject: "Complex work becomes safer when each part can be checked",
    title: "One Job at a Time",
    tagline: "Split the mega-task before it splits your brain.",
    artifact: "plan",
    task: "SCENARIO: Your committee asks an agent to 'organise Open House'. That hides dozens of decisions and dependencies.\n\nYOUR TASK: Prompt the agent to decompose the work into phases and checkable tasks. Show dependencies, owners, inputs and outputs. Add a checkpoint between planning and anything that contacts people, spends money or publishes information.",
    rubric: ["goal", "decomposition", "steps", "checkpoints", "done"],
    mockOutputs: planOutputs("Open House Work Breakdown", "Deliver an approved Open House plan before any external action begins.", ["List constraints and unresolved decisions; output a decision log owned by the teacher-in-charge.", "Map workstreams for programme, venue, visitors, publicity and safety; name an owner and deliverable for each.", "Sequence dependencies, including confirmed rooms before printing maps.", "Hold a human approval checkpoint for budget, public copy and external messages.", "After approval, execute each workstream and record completion evidence."], ["Every task has an owner, dependency and visible output.", "No spending, publishing or external contact happens before approval.", "The final run sheet, safety check and contact list are approved."]),
  },

  // AGENTIC AI
  {
    id: "a1",
    category: "agents",
    subject: "Chatbots answer; agents pursue goals with tools",
    title: "Bot, Copilot or Agent?",
    tagline: "Same AI label. Very different levels of control.",
    task: "Identify how much autonomy each system has and what that changes.",
    items: [
      { id: "a1-1", prompt: "It answers your question, then waits. What is it acting like?", options: ["Chatbot", "Copilot", "Agent"], answerIndex: 0, hint: "It takes no action beyond replying.", explanation: "Chatbot. It responds turn by turn and does not independently pursue a longer goal." },
      { id: "a1-2", prompt: "It drafts an email, but you review and press Send. What is it acting like?", options: ["Chatbot", "Copilot", "Agent"], answerIndex: 1, hint: "The human still performs the consequential action.", explanation: "Copilot. It assists the person while the person remains in control of the workflow." },
      { id: "a1-3", prompt: "It checks stock every hour, places an approved order and records the receipt. What is it acting like?", options: ["Chatbot", "Copilot", "Agent"], answerIndex: 2, hint: "Look for a goal, repeated observation and tool use.", explanation: "Agent. It continues across steps, observes state and uses tools to act within its permissions." },
      { id: "a1-4", prompt: "Which change most increases risk?", options: ["A friendlier tone", "Access to tools that affect real systems", "A shorter answer", "A new avatar"], answerIndex: 1, hint: "Which option changes consequences outside the chat?", explanation: "Tool access increases the possible impact. Sending, deleting, purchasing or publishing requires stronger boundaries and oversight." },
    ],
  },
  {
    id: "a2",
    category: "agents",
    subject: "Give an agent only the tools and permissions it needs",
    title: "Tool Belt",
    tagline: "Useful access in. Dangerous access out.",
    artifact: "plan",
    task: "SCENARIO: An agent will help organise homework reminders from the class calendar. It can read events, draft reminders and post to the class channel. It must never read private chats or edit the official calendar.\n\nYOUR TASK: Prompt it to write an operating plan. Match each step to an allowed tool, state forbidden tools and data, use the least access needed, and require approval before the first public post.",
    rubric: ["goal", "steps", "tools", "permissions", "checkpoints"],
    mockOutputs: planOutputs("Homework Reminder Agent", "Post accurate reminders from the official calendar without accessing private data or changing source records.", ["Read assignment title, due date and teacher note from the class calendar using read-only access.", "Draft one concise reminder and link back to the source event.", "Send the first draft to the class rep for approval; wait.", "Post only approved text to the class channel.", "Never open private chats, edit calendar events or message students individually."], ["Every reminder matches a source event.", "Only the class calendar and class channel were accessed.", "The first public post has recorded approval."]),
  },
  {
    id: "a3",
    category: "agents",
    subject: "Consequential actions need human checkpoints",
    title: "Checkpoint or Full Send?",
    tagline: "Know when the agent must pause.",
    task: "Choose where a person should review an agent's work before it acts.",
    items: [
      { id: "a3-1", prompt: "The agent fixes spelling in a private draft. Pause for approval?", options: ["Usually yes", "Usually no"], answerIndex: 1, hint: "Consider how reversible and private the change is.", explanation: "Usually no. A private, reversible edit can be reviewed in the normal drafting flow." },
      { id: "a3-2", prompt: "The agent is about to email all parents. Pause for approval?", options: ["Yes", "No"], answerIndex: 0, hint: "Consider audience size and whether the action can be taken back.", explanation: "Yes. A mass external message is consequential and hard to recall once sent." },
      { id: "a3-3", prompt: "The agent wants to delete duplicate files permanently. Pause for approval?", options: ["Yes", "No"], answerIndex: 0, hint: "What happens if its duplicate detector is wrong?", explanation: "Yes. Permanent deletion needs target confirmation and preferably a recoverable trash step." },
      { id: "a3-4", prompt: "What is the best checkpoint design?", options: ["Ask approval after acting", "Show the exact action, target and consequence before acting", "Ask 'Are you sure?' with no details", "Let the agent decide"], answerIndex: 1, hint: "A person needs enough information to make a real decision.", explanation: "Show the exact action, target and consequence. A vague confirmation is not meaningful oversight." },
    ],
  },
  {
    id: "a4",
    category: "agents",
    subject: "Memory should be useful, limited and visible",
    title: "Memory Lane",
    tagline: "Remember the preference, forget the private detail.",
    task: "Decide what an assistant should remember and what should stay out of long-term memory.",
    items: [
      { id: "a4-1", prompt: "A student asks the assistant to remember that they prefer bullet-point explanations.", options: ["Reasonable to remember", "Do not remember"], answerIndex: 0, hint: "Is this a low-risk preference that improves future help?", explanation: "Reasonable, if the student can view and delete it. It is a useful preference with low sensitivity." },
      { id: "a4-2", prompt: "The assistant sees a classmate's medical detail in an uploaded chat screenshot.", options: ["Save it for context", "Do not store it"], answerIndex: 1, hint: "The person did not provide consent, and the detail is sensitive.", explanation: "Do not store it. It belongs to someone else, is sensitive and is unnecessary for future assistance." },
      { id: "a4-3", prompt: "A system remembers information forever but gives users no way to inspect it. What is missing?", options: ["A brighter interface", "Transparency and user control", "More storage", "A longer prompt"], answerIndex: 1, hint: "People should know what persists and be able to change it.", explanation: "Memory needs transparency and control: what is saved, why, for how long, and how to correct or delete it." },
      { id: "a4-4", prompt: "What is a good default memory rule?", options: ["Save everything", "Save the minimum needed for a clear purpose", "Save secrets first", "Never tell the user"], answerIndex: 1, hint: "More stored data creates more exposure.", explanation: "Store the minimum needed for a clear purpose. Useful memory should not become invisible surveillance." },
    ],
  },
  {
    id: "a5",
    category: "agents",
    subject: "Agents need failure rules, recovery paths and a stop button",
    title: "Agent Gone Sideways",
    tagline: "When the plan breaks, don't let it freestyle.",
    artifact: "plan",
    task: "SCENARIO: An agent prepares a weekly canteen pre-order list. Sometimes names are missing, totals disagree or the order service rejects a request. Silent retries could duplicate an order.\n\nYOUR TASK: Prompt it to create a run plan with validation checks, safe retries, escalation rules, a maximum retry count and a clear stop condition. It must keep an audit log and never invent missing student choices.",
    rubric: ["steps", "verification", "recovery", "boundaries", "done"],
    mockOutputs: planOutputs("Canteen Pre-order Run", "Submit one accurate order, with no duplicated or invented student choice.", ["Validate every row against the class list and flag blanks; do not fill them in.", "Compare item counts with the payment total before submission.", "Show the final order summary to the class rep for approval.", "Submit once and record the order ID and response.", "On a timeout, check order status before one retry; on a second failure, stop and escalate."], ["Every submitted row maps to a confirmed student choice.", "There is exactly one recorded order ID.", "The log shows checks, approval, submission and any failure.", "Two failures or a total mismatch stops the run."]),
  },

  // TRUTH AND MEDIA LITERACY
  {
    id: "t1",
    category: "truth",
    subject: "Trace important claims back to evidence",
    title: "Source Detective",
    tagline: "Follow the claim until you hit the original.",
    task: "Choose the strongest next move when checking a claim.",
    items: [
      { id: "t1-1", prompt: "A viral post says 'a new study proves homework never helps' but gives no link. What should you do first?", options: ["Share it cautiously", "Search for the named study or original research", "Ask a chatbot if it sounds true", "Count the likes"], answerIndex: 1, hint: "Move closer to the original evidence, not another reaction to it.", explanation: "Find the original study. Then check what it actually measured, who was studied and whether the post exaggerated the conclusion." },
      { id: "t1-2", prompt: "Three websites repeat the exact same statistic and wording. Is that three independent sources?", options: ["Yes", "Not necessarily"], answerIndex: 1, hint: "They may all be copying one origin.", explanation: "Not necessarily. Trace their links and wording. Ten copies of one unsupported claim still equal one unsupported claim." },
      { id: "t1-3", prompt: "Which source is strongest for a school's official exam timetable?", options: ["A student's repost", "The school's dated official notice", "An undated study blog", "A generated summary"], answerIndex: 1, hint: "Choose the authority responsible for publishing the schedule.", explanation: "Use the school's dated official notice. Match the source to the claim and check that it is current." },
      { id: "t1-4", prompt: "A source supports a claim but was published twelve years ago. What else matters?", options: ["Only its logo", "Whether the topic could have changed", "How confident it sounds", "How many ads it has"], answerIndex: 1, hint: "Some facts are stable; policies, prices and statistics often are not.", explanation: "Check whether the information is time-sensitive. An old source can be excellent history and poor evidence for the current situation." },
    ],
  },
  {
    id: "t2",
    category: "truth",
    subject: "Confidence, length and detail are not evidence",
    title: "Confidence Costume",
    tagline: "Strip off the polish. What supports the claim?",
    task: "Judge answers by evidence and reasoning instead of presentation.",
    items: [
      { id: "t2-1", prompt: "Answer A is smooth and certain but cites nothing. Answer B is cautious and links primary evidence. Which deserves more trust?", options: ["Answer A", "Answer B"], answerIndex: 1, hint: "Trust should rise with evidence, not confidence.", explanation: "Answer B. Appropriate uncertainty plus traceable evidence is stronger than unsupported fluency." },
      { id: "t2-2", prompt: "An AI gives a percentage to one decimal place. What does that precision prove?", options: ["It used a database", "Nothing by itself", "It ran an experiment", "The claim is recent"], answerIndex: 1, hint: "A precise number can still be invented.", explanation: "Nothing by itself. Ask where the number came from, what was measured and when." },
      { id: "t2-3", prompt: "Two answers disagree. What is the strongest response?", options: ["Pick the longer one", "Find the claims that differ and check them against suitable sources", "Ask each to be more confident", "Average the answers"], answerIndex: 1, hint: "Turn a vague disagreement into specific checkable claims.", explanation: "Isolate the disagreement and verify each claim. Sometimes both answers contain part of the truth or rely on different dates and definitions." },
      { id: "t2-4", prompt: "When is 'I don't know yet' a strong answer?", options: ["Never", "When evidence is missing or the question cannot be resolved safely", "Only in exams", "When the response is short"], answerIndex: 1, hint: "Uncertainty can prevent a guess from becoming a false fact.", explanation: "It is strong when evidence is missing. A reliable system should expose uncertainty and suggest a way to investigate.", },
    ],
  },
  {
    id: "t3",
    category: "truth",
    subject: "Data can mislead when the sample or measurement is weak",
    title: "Garbage In, Garbage Out",
    tagline: "The model learned it somewhere. Check the somewhere.",
    task: "Spot data problems before they become confident predictions.",
    items: [
      { id: "t3-1", prompt: "A study of student sleep surveys only members of a 6am running club. What is the main problem?", options: ["The sample may not represent all students", "The survey has words", "Running is unhealthy", "The result needs AI"], answerIndex: 0, hint: "Who is missing from the sample?", explanation: "The sample is unrepresentative. Early runners may have very different routines from the wider student population." },
      { id: "t3-2", prompt: "Ice-cream sales and sunburn both rise in hot weather. Does ice cream cause sunburn?", options: ["Yes", "No, heat or sunlight may influence both"], answerIndex: 1, hint: "Look for a third factor connected to both measurements.", explanation: "No. Correlation alone does not show causation. Hot, sunny weather can increase both ice-cream buying and sun exposure." },
      { id: "t3-3", prompt: "A face model was trained mostly on one skin tone. What should evaluators do?", options: ["Report only overall accuracy", "Test performance across represented and underrepresented groups", "Make the logo inclusive", "Use fewer test cases"], answerIndex: 1, hint: "An average can hide uneven errors.", explanation: "Evaluate by relevant groups and conditions. If performance is uneven, improve the data or limit use rather than hiding the gap." },
      { id: "t3-4", prompt: "A recommendation system learns only from clicks. What might it confuse?", options: ["Attention with genuine value", "Text with images", "Students with teachers", "Wi-Fi with electricity"], answerIndex: 0, hint: "People click for many reasons, including shock and curiosity.", explanation: "Clicks measure attention, not necessarily usefulness, truth or wellbeing. The chosen metric shapes what the system optimises." },
    ],
  },
  {
    id: "t4",
    category: "truth",
    subject: "Generated content can target emotion and identity",
    title: "Persuasion Engine",
    tagline: "If it makes you furious fast, slow down.",
    task: "Recognise manipulation tactics in personalised AI content.",
    items: [
      { id: "t4-1", prompt: "A clip triggers outrage and says 'share before they delete this'. What is the best first move?", options: ["Share quickly", "Pause and verify the source and full context", "Comment in all caps", "Ask for more dramatic clips"], answerIndex: 1, hint: "Urgency can be used to stop you checking.", explanation: "Pause and verify. Emotional urgency is a persuasion tactic, not evidence that the claim is true." },
      { id: "t4-2", prompt: "Why can personalised AI persuasion be especially powerful?", options: ["It can adapt wording to a person's interests or fears", "It always tells the truth", "It removes all emotion", "It cannot scale"], answerIndex: 0, hint: "The same message need not be shown to everyone.", explanation: "AI can produce many tailored versions cheaply, matching language and appeals to different audiences." },
      { id: "t4-3", prompt: "A voice note sounds exactly like your friend asking for money. What matters most?", options: ["The voice quality", "Verification through a separate trusted channel", "The message length", "Whether it uses slang"], answerIndex: 1, hint: "A realistic voice can be cloned.", explanation: "Verify using another trusted channel or a shared fact. Do not rely on the sound of the voice alone." },
      { id: "t4-4", prompt: "What is confirmation bias?", options: ["Preferring information that supports what you already believe", "Changing your mind after evidence", "Checking several sources", "Admitting uncertainty"], answerIndex: 0, hint: "Think about which evidence feels easiest to accept.", explanation: "Confirmation bias makes supporting claims feel more convincing and opposing evidence easier to dismiss. Deliberately test your view against strong counter-evidence." },
    ],
  },

  // RESPONSIBLE CREATION AND ETHICS
  {
    id: "e1",
    category: "responsibility",
    subject: "Fair systems require more than a strong average",
    title: "The Missing Majority",
    tagline: "Who benefits? Who gets the errors?",
    task: "Identify fairness problems and the questions a responsible team should ask.",
    items: [
      { id: "e1-1", prompt: "An AI selects students for a programme using last year's teacher nominations. What should the team examine?", options: ["Only model speed", "Whether past nominations contain unequal opportunities or bias", "The font", "Whether the list is alphabetical"], answerIndex: 1, hint: "Historical decisions are not automatically fair training labels.", explanation: "Past nominations may reflect unequal access, visibility or expectations. Automating them can repeat those patterns at scale." },
      { id: "e1-2", prompt: "A translation tool works well for formal English but poorly for local expressions. What is a responsible response?", options: ["Hide the limitation", "Test with relevant users and state where it fails", "Blame users", "Use it for higher-stakes decisions"], answerIndex: 1, hint: "A tool should be evaluated in the language people actually use.", explanation: "Test with relevant users, improve representation and communicate limitations. Do not present narrow performance as universal." },
      { id: "e1-3", prompt: "Who should help evaluate an AI system used by students with disabilities?", options: ["Only the vendor", "Affected students and accessibility experts, alongside the school", "Nobody until launch", "Only the fastest users"], answerIndex: 1, hint: "People affected by a system hold knowledge the builders may not have.", explanation: "Include affected students and accessibility expertise early. Participation helps reveal barriers that aggregate testing misses." },
      { id: "e1-4", prompt: "Fairness always means giving everyone exactly the same treatment. True?", options: ["True", "False"], answerIndex: 1, hint: "Equal inputs can still create unequal access or outcomes.", explanation: "False. Fairness may require accommodation, different support or careful attention to outcomes, depending on the context." },
    ],
  },
  {
    id: "e2",
    category: "responsibility",
    subject: "Consent, privacy and ownership still matter when creation is easy",
    title: "Should You Upload That?",
    tagline: "Useful prompt, unnecessary personal data.",
    task: "Reduce privacy and ownership risks before using AI.",
    items: [
      { id: "e2-1", prompt: "You want help rewriting a conflict message. What is the best input?", options: ["The full chat with names and phone numbers", "A short anonymised summary with only relevant details", "Everyone's contact list", "A private voice recording"], answerIndex: 1, hint: "Give the minimum context needed for useful help.", explanation: "Use an anonymised summary. Remove names, contacts, unrelated screenshots and details that identify other people." },
      { id: "e2-2", prompt: "A tool can generate an image in a living artist's style. What should you consider before publishing it?", options: ["Only whether it looks good", "Consent, platform rules, attribution and whether the imitation misleads", "Nothing because AI made it", "Only file size"], answerIndex: 1, hint: "Generation does not erase questions of labour, identity and permission.", explanation: "Consider consent, applicable rules, attribution and misrepresentation. Being technically possible does not settle whether a use is fair." },
      { id: "e2-3", prompt: "A friend shared a photo privately. Can you upload it to an AI editor without asking?", options: ["Yes, because you have the file", "No, access is not the same as consent for a new use"], answerIndex: 1, hint: "Permission can depend on purpose and audience.", explanation: "No. Ask before giving someone else's image to another service or using it for a new purpose." },
      { id: "e2-4", prompt: "What should an AI-use disclosure say?", options: ["AI was used", "Which tool helped, what it did and what the human checked or changed", "Nothing specific", "The model is always correct"], answerIndex: 1, hint: "A useful disclosure lets someone understand the division of work.", explanation: "Name the tool's role and the human contribution. The right level of detail depends on the assignment or publication rules." },
    ],
  },
  {
    id: "e3",
    category: "responsibility",
    subject: "Humans remain accountable for consequential decisions",
    title: "Who Owns the Decision?",
    tagline: "AI advised. A human still has to answer for it.",
    task: "Decide where human judgment and accountability must remain visible.",
    items: [
      { id: "e3-1", prompt: "An AI flags a student as likely to fail. What should happen next?", options: ["Punish the student automatically", "A qualified person reviews evidence, context and possible errors before offering support", "Publish the score", "Treat probability as destiny"], answerIndex: 1, hint: "A prediction is not a complete explanation of a person.", explanation: "Human review is essential. Use the signal to offer support, not to label or punish, and allow errors to be challenged." },
      { id: "e3-2", prompt: "A school says, 'The algorithm rejected the application, so nobody is responsible.' Is that acceptable?", options: ["Yes", "No"], answerIndex: 1, hint: "People chose the tool, rules, data and way it would be used.", explanation: "No. The organisation remains responsible for the decision process, its safeguards and a meaningful appeal route." },
      { id: "e3-3", prompt: "What does meaningful human oversight require?", options: ["A person clicks Approve without time to read", "Authority, information and time to question or stop the system", "A hidden log", "A human name on the screen"], answerIndex: 1, hint: "Oversight must be able to change the outcome.", explanation: "The reviewer needs enough context, real authority and time. A ceremonial click is not oversight." },
      { id: "e3-4", prompt: "When should AI not make the final call by itself?", options: ["When consequences are serious and judgment or rights are involved", "When the interface is colourful", "When the answer is short", "Only when Wi-Fi is slow"], answerIndex: 0, hint: "Think about harm, contestability and irreversible outcomes.", explanation: "High-impact decisions need human responsibility, safeguards and ways for affected people to question the result." },
    ],
  },
  {
    id: "e4",
    category: "responsibility",
    subject: "Use AI to extend your thinking, not replace your authorship",
    title: "Keep Your Voice",
    tagline: "AI can help. The work still needs to be yours.",
    task: "Choose collaboration habits that preserve learning, honesty and human contribution.",
    items: [
      { id: "e4-1", prompt: "Which workflow best preserves authorship?", options: ["Submit the first generated draft", "Write your view, ask for critique, revise and verify in your own words", "Hide AI use", "Ask AI to imitate a classmate"], answerIndex: 1, hint: "The human should make the key choices and be able to explain them.", explanation: "Start from your thinking, use AI for feedback, then revise and verify. You should be able to defend every claim and choice." },
      { id: "e4-2", prompt: "AI gives you an argument you do not understand. What should you do?", options: ["Use it because it sounds advanced", "Ask questions, check it and leave it out if you still cannot explain it", "Add longer words", "Remove the disclosure"], answerIndex: 1, hint: "Ownership includes understanding what you submit.", explanation: "Investigate until you understand. If you cannot explain or verify the argument, it should not appear as your reasoning." },
      { id: "e4-3", prompt: "What is a strong human contribution in an AI-assisted project?", options: ["Pressing Generate", "Choosing the purpose, applying lived context, verifying and making final decisions", "Copying faster", "Keeping the process secret"], answerIndex: 1, hint: "Think about judgment the model cannot own for you.", explanation: "Purpose, context, taste, verification and accountability are substantial human contributions. Record them rather than treating generation as the whole process." },
      { id: "e4-4", prompt: "When is not using AI the better choice?", options: ["When the task exists to practise the exact skill AI would replace, or rules prohibit it", "Never", "Only when the answer is easy", "Whenever a friend dislikes technology"], answerIndex: 0, hint: "A tool can defeat the purpose of an exercise.", explanation: "Skip AI when it removes the learning the task is designed to build, violates rules, exposes sensitive data or adds needless risk." },
    ],
  },
];
